<?xml version="1.0" encoding="utf-8"?><Database Name="Company" Class="CompanyServicesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tcp:s6yf346b47.database.windows.net,1433;Initial Catalog=Company;User ID=bernardoamf@s6yf346b47;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="CompanyServices.Data.Properties.Settings" SettingsPropertyName="CompanyConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>